config:
  deployment:
    namespace: ns-trax-dev

  tls:
    hosts:
      frontend: app.traxxia.ai
      backend: api.traxxia.ai
      mlbackend: mlbe.traxxia.ai
    # secretName: traxxia-tls
    secretName: traxxia-ssl-wc

  service:
    frontend: traxxia-frontend-service
    backend: traxxia-backend-service
    mlbackend: traxxia-mlbackend-service
    port:
      frontend: 80
      backend: 5000
      mlbackend: 8000
    
  azure:
    clientId: 59682913-7dc9-490b-bd03-d181863ee5b0