apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "traxxia.fullname" . }}-frontend-deployment
  namespace: {{ .Values.frontend.deployment.namespace }}
spec:
  replicas: {{ .Values.frontend.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ include "traxxia.name" . }}-frontend-app
  template:
    metadata:
      labels:
        app: {{ include "traxxia.name" . }}-frontend-app
    spec:
      nodeSelector:
        agentpool: {{ .Values.frontend.deployment.nodeSelectorLabel }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: "{{ .Values.frontend.image.pullPolicy }}"
          ports:
            - containerPort: {{ .Values.frontend.application.containerPort }}