apiVersion: v1
kind: Service
metadata:
  name: {{ include "traxxia.fullname" . }}-frontend-service
  namespace: {{ .Values.traxxiafrontend.aksconfig.namespace }}
spec:
  type: {{ .Values.traxxiafrontend.service.type }}
  # loadBalancerIP: {{ .Values.traxxiafrontend.service.ip }}
  selector:
    app: {{ include "traxxia.name" . }}-frontend-app
  ports:
    - protocol: TCP
      port: {{ .Values.traxxiafrontend.service.port }}
      targetPort: {{ .Values.traxxiafrontend.app.port }}
