mlbackend:
  image:
    repository: traxdevacr.azurecr.io/trax_dev_ml_backend
    tag: latest
    pullPolicy: Always

  service:
    name: traxxia-mlbackend-service
    type: ClusterIP
    port: 8000

  application:
    containerPort: 8000

  deployment:
    nodeSelectorLabel: userpool
    namespace: ns-trax-dev
    replicas: 2
    resources:
      limits:
        cpu: "1"
        memory: 2G
      requests:
        cpu: "1"
        memory: 2G

  azure:
    keyVaultName: trax-dev-akv
    resourceGroup: trax-dev-core-rg
    tenantId: 3e737f0d-eee3-42c1-8c0f-cfd3e6f7053a
    clientId: 59682913-7dc9-490b-bd03-d181863ee5b0

  aks:
    secretName: mlbackend-secret
    serviceAccount: traxxia-aks-sa

  environment: 
    LANGFUSE_BASE_URL: "https://us.cloud.langfuse.com"
    LANGFUSE_OPENAI_AUTO_INSTRUMENT: "true"

  keyVault:
    secrets:
      - name: NEWSAPI-API-KEY
        alias: NEWSAPI_API_KEY
      - name: OPENAI-API-KEY
        alias: OPENAI_API_KEY
      - name: ALPHA-VANT-API-KEY
        alias: ALPHA_VANT_API_KEY
      - name: GROQ-API-KEY
        alias: GROQ_API_KEY
      - name: PERPLEXITY-API-KEY
        alias: PERPLEXITY_API_KEY
      - name: LANGFUSE-SECRET-KEY 
        alias: LANGFUSE_SECRET_KEY
      - name: LANGFUSE-PUBLIC-KEY
        alias: LANGFUSE_PUBLIC_KEY