apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nuclios.fullname" . }}-frontend-ingress
  namespace: {{ .Values.nucliosfrontend.aksconfig.namespace }}
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "nuclios.fullname" . }}-frontend-service
            port:
              number: {{ .Values.nucliosfrontend.service.port }}
