frontend:
  image:
    repository: traxdevacr.azurecr.io/trax_dev_frontend
    tag: latest
    pullPolicy: Always

  deployment:
    namespace: ns-trax-dev
    replicas: 2
    nodeSelectorLabel: userpool
    resources:
      limits:
        cpu: "2"
        memory: 4G
      requests:
        cpu: "2"
        memory: 4G

  service:
    name: traxxia-frontend-service
    type: ClusterIP
    port: 80
    
  application:
    containerPort: 8080

  environment:
    REACT_APP_BACKEND_URL: "https://api.traxxia.ai"