apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "nuclios.fullname" . }}-backend-spc
  namespace: {{ .Values.nucliosbackend.aksconfig.namespace }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ .Values.nucliosbackend.akssecretname }}
      type: Opaque
      data:
        - objectName: APPLICATIONINSIGHTSCONNECTIONSTRING
          key: APPLICATIONINSIGHTS_CONNECTION_STRING
        - objectName: APPINSIGHTSINSTRUMENTATIONKEYNEW
          key: APPINSIGHTS_INSTRUMENTATIONKEY
        - objectName: AZUREFILESHARECONNECTIONSTRING
          key: AZURE_FILE_SHARE_CONNECTION_STRING
        - objectName: AZUREOAUTHAPPLICATIONID
          key: AZURE_OAUTH_APPLICATION_ID
        - objectName: AZUREOAUTHCLIENTSECRET
          key: AZURE_OAUTH_CLIENT_SECRET
        - objectName: AZUREOAUTHSCOPE
          key: AZURE_OAUTH_SCOPE
        - objectName: AZUREOAUTHTENANCY
          key: AZURE_OAUTH_TENANCY
        - objectName: CHATGPTOPENAIKEY
          key: CHATGPT_OPENAI_KEY
        - objectName: DATAAZURECONNECTIONSTRING
          key: DATA_AZURE_CONNECTION_STRING
        - objectName: DOCKERREGISTRYSERVERPASSWORD
          key: DOCKER_REGISTRY_SERVER_PASSWORD
        - objectName: DOCKERREGISTRYSERVERURL
          key: DOCKER_REGISTRY_SERVER_URL
        - objectName: DOCKERREGISTRYSERVERUSERNAME
          key: DOCKER_REGISTRY_SERVER_USERNAME
        - objectName: JWTPRIVATEKEYENCODED
          key: JWT_PRIVATE_KEY_ENCODED
        - objectName: JWTPUBLICKEYENCODED
          key: JWT_PUBLIC_KEY_ENCODED
        - objectName: SAMLENCRYPTIONKEY
          key: SAML_ENCRYPTION_KEY
        - objectName: SHAREEMAILPWD
          key: SHARE_EMAIL_PWD
        - objectName: SQLALCHEMYDATABASEURI
          key: SQLALCHEMY_DATABASE_URI
        - objectName: TOKENSECRETKEY
          key: TOKEN_SECRET_KEY
        - objectName: DATABRICKPAT
          key: DATABRICK_PAT
        - objectName: CRYPTOENCRYPTIONKEY
          key: CRYPTO_ENCRYPTION_KEY
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.nucliosbackend.azure.clientId }}"
    tenantId: "{{ .Values.nucliosbackend.azure.tenantId }}"
    resourceGroup: "{{ .Values.nucliosbackend.azure.resourceGroup }}"
    keyvaultName: "{{ .Values.nucliosbackend.azure.keyVaultName }}"
    objects: |
      array:
        - |
          objectName: APPLICATIONINSIGHTSCONNECTIONSTRING
          objectType: secret
        - |
          objectName: APPINSIGHTSINSTRUMENTATIONKEYNEW
          objectType: secret
        - |
          objectName: AZUREFILESHARECONNECTIONSTRING
          objectType: secret
        - |
          objectName: AZUREOAUTHAPPLICATIONID
          objectType: secret
        - |
          objectName: AZUREOAUTHCLIENTSECRET
          objectType: secret
        - |
          objectName: AZUREOAUTHSCOPE
          objectType: secret
        - |
          objectName: AZUREOAUTHTENANCY
          objectType: secret
        - |
          objectName: CHATGPTOPENAIKEY
          objectType: secret
        - |
          objectName: DATAAZURECONNECTIONSTRING
          objectType: secret
        - |
          objectName: DOCKERREGISTRYSERVERPASSWORD
          objectType: secret
        - |
          objectName: DOCKERREGISTRYSERVERURL
          objectType: secret
        - |
          objectName: DOCKERREGISTRYSERVERUSERNAME
          objectType: secret
        - |
          objectName: JWTPRIVATEKEYENCODED
          objectType: secret
        - |
          objectName: JWTPUBLICKEYENCODED
          objectType: secret
        - |
          objectName: SAMLENCRYPTIONKEY
          objectType: secret
        - |
          objectName: SHAREEMAILPWD
          objectType: secret
        - |
          objectName: SQLALCHEMYDATABASEURI
          objectType: secret
        - |
          objectName: TOKENSECRETKEY
          objectType: secret
        - |
          objectName: DATABRICKPAT
          objectType: secret
        - |
          objectName: CRYPTOENCRYPTIONKEY
          objectType: secret
    syncSecret.enabled: "true"