apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nuclios.fullname" . }}-backend-config
  namespace: {{ .Values.nucliosbackend.aksconfig.namespace }}
data:
{{- range $key, $val := .Values.config }}
  {{ $key }}: "{{ $val }}"
{{- end }}
