apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "traxxia.fullname" . }}-mlbackend-spc
  namespace: {{ .Values.mlbackend.deployment.namespace }}
  annotations:
    secrets-store.csi.k8s.io/rotation-poll-interval: "2m"
spec:
  provider: azure
  secretObjects:
    - secretName: {{ .Values.mlbackend.aks.secretName }}
      type: Opaque
      data:
        - objectName: NEWSAPI-API-KEY
          key: NEWSAPI_API_KEY
        - objectName: OPENAI-API-KEY
          key: OPENAI_API_KEY
        - objectName: ALPHA-VANT-API-KEY
          key: ALPHA_VANT_API_KEY
        - objectName: GROQ-API-KEY
          key: GROQ_API_KEY
        - objectName: PERPLEXITY-API-KEY
          key: PERPLEXITY_API_KEY
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.mlbackend.azure.clientId }}"
    tenantId: "{{ .Values.mlbackend.azure.tenantId }}"
    resourceGroup: "{{ .Values.mlbackend.azure.resourceGroup }}"
    keyvaultName: "{{ .Values.mlbackend.azure.keyVaultName }}"
    objects: |
      array:
        - |
          objectName: NEWSAPI-API-KEY
          objectType: secret
        - |
          objectName: OPENAI-API-KEY
          objectType: secret
        - |
          objectName: ALPHA-VANT-API-KEY
          objectType: secret
        - |
          objectName: GROQ-API-KEY
          objectType: secret
        - |
          objectName: PERPLEXITY-API-KEY
          objectType: secret
    syncSecret.enabled: "true"