apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mlbackend.service.name }}
  namespace: {{ .Values.mlbackend.deployment.namespace }}
spec:
  type: {{ .Values.mlbackend.service.type }}
  selector:
    app: {{ include "traxxia.name" . }}-mlbackend-app
  ports:
    - protocol: TCP
      port: {{ .Values.mlbackend.service.port }}
      targetPort: {{ .Values.mlbackend.application.containerPort }}
