apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "traxxia.fullname" . }}-mlbackend-deployment
  namespace: {{ .Values.mlbackend.deployment.namespace }}
spec:
  replicas: {{ .Values.mlbackend.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ include "traxxia.name" . }}-mlbackend-app
  template:
    metadata:
      annotations:
        secrets-store.csi.k8s.io/refresh: "true"
      labels:
        app: {{ include "traxxia.name" . }}-mlbackend-app
    spec:
      serviceAccountName: {{ .Values.mlbackend.aks.serviceAccount }}
      nodeSelector:
        agentpool: {{ .Values.mlbackend.deployment.nodeSelectorLabel }}
      containers:
        - name: mlbackend
          image: "{{ .Values.mlbackend.image.repository }}:{{ .Values.mlbackend.image.tag }}"
          imagePullPolicy: "{{ .Values.mlbackend.image.pullPolicy }}"
          ports:
            - containerPort: {{ .Values.mlbackend.application.containerPort }}
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          env:
            {{- range .Values.mlbackend.keyVault.secrets }}
            - name: {{ .alias }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.mlbackend.aks.secretName }}
                  key: {{ .alias }}
            {{- end }}

      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "traxxia.fullname" . }}-mlbackend-spc
