apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "traxxia.fullname" . }}-ingress
  namespace: {{ .Values.config.deployment.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "8m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-next-upstream: "error timeout invalid_header http_502 http_503 http_504"
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "3"
spec:
  tls:
  - hosts:
      - {{ .Values.config.tls.hosts.frontend }}
      - {{ .Values.config.tls.hosts.backend }}
      - {{ .Values.config.tls.hosts.mlbackend }}
    secretName: {{ .Values.config.tls.secretName }}
  rules:
  - host: {{ .Values.config.tls.hosts.frontend }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.config.service.frontend }}
            port:
              number: {{ .Values.config.service.port.frontend }}
  - host: {{ .Values.config.tls.hosts.backend }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.config.service.backend }}
            port:
              number: {{ .Values.config.service.port.backend }}
  - host: {{ .Values.config.tls.hosts.mlbackend }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.config.service.mlbackend }}
            port:
              number: {{ .Values.config.service.port.mlbackend }}
