apiVersion: v1
kind: ServiceAccount
metadata:
  name: traxxia-aks-sa
  namespace: {{ .Values.config.deployment.namespace }}
  annotations:
    azure.workload.identity/client-id: "{{ .Values.config.azure.clientId }}"
