apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "traxxia.fullname" . }}-backend-spc
  namespace: {{ .Values.backend.deployment.namespace }}
  annotations:
    secrets-store.csi.k8s.io/rotation-poll-interval: "2m"
spec:
  provider: azure
  secretObjects:
    - secretName: {{ .Values.backend.aks.secretName }}
      type: Opaque
      data:
        - objectName: MONGO-URI
          key: MONGO_URI
        - objectName: SECRET-KEY
          key: SECRET_KEY
        - objectName: ENCRYPTION-KEY
          key: ENCRYPTION_KEY
        - objectName: AZURE-STORAGE-KEY
          key: AZURE_STORAGE_KEY
        - objectName: STRIPE-PUBLISHABLE-KEY
          key: STRIPE_PUBLISHABLE_KEY
        - objectName: STRIPE-SECRET-KEY
          key: STRIPE_SECRET_KEY
        - objectName: AZURE-STORAGE-ACCOUNT
          key: AZURE_STORAGE_ACCOUNT  
        - objectName: AZURE-STORAGE-CONTAINER
          key: AZURE_STORAGE_CONTAINER  

        - objectName: OBSERVATORY-PASSWORD
          key: OBSERVATORY_PASSWORD
        - objectName: MS-TENANT-ID
          key: MS_TENANT_ID
        - objectName: MS-CLIENT-ID
          key: MS_CLIENT_ID
        - objectName: MS-CLIENT-SECRET
          key: MS_CLIENT_SECRET 
        - objectName: MS-SENDER
          key: MS_SENDER
        - objectName: FRONTEND-URL
          key: FRONTEND_URL
        - objectName: MAX-FILE-UPLOAD-LIMIT
          key: MAX_FILE_UPLOAD_LIMIT
        - objectName: MAX-FILE-SIZE-MB
          key: MAX_FILE_SIZE_MB
        - objectName: NO-PLAN-BUSINESS-LIMIT
          key: NO_PLAN_BUSINESS_LIMIT
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.backend.azure.clientId }}"
    tenantId: "{{ .Values.backend.azure.tenantId }}"
    resourceGroup: "{{ .Values.backend.azure.resourceGroup }}"
    keyvaultName: "{{ .Values.backend.azure.keyVaultName }}"
    objects: |
      array:
        - |
          objectName: MONGO-URI
          objectType: secret
        - |
          objectName: SECRET-KEY
          objectType: secret
        - |
          objectName: ENCRYPTION-KEY
          objectType: secret
        - |
          objectName: AZURE-STORAGE-KEY
          objectType: secret
        - |
          objectName: STRIPE-PUBLISHABLE-KEY
          objectType: secret
        - |
          objectName: STRIPE-SECRET-KEY
          objectType: secret
        - |
          objectName: AZURE-STORAGE-ACCOUNT 
          objectType: secret
        - |
          objectName: AZURE-STORAGE-CONTAINER 
          objectType: secret

        - |
          objectName: OBSERVATORY-PASSWORD  
          objectType: secret
        - |
          objectName: MS-TENANT-ID
          objectType: secret
        - |
          objectName: MS-CLIENT-ID
          objectType: secret
        - |
          objectName: MS-CLIENT-SECRET
          objectType: secret
        - |
          objectName: MS-SENDER
          objectType: secret
        - |
          objectName: FRONTEND-URL
          objectType: secret
        - |
          objectName: MAX-FILE-UPLOAD-LIMIT     
          objectType: secret
        - |
          objectName: MAX-FILE-SIZE-MB     
          objectType: secret
        - |
          objectName: NO-PLAN-BUSINESS-LIMIT     
          objectType: secret
    syncSecret.enabled: "true"