apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "traxxia.fullname" . }}-backend-spc
  namespace: {{ .Values.backend.deployment.namespace }}
  annotations:
    secrets-store.csi.k8s.io/rotation-poll-interval: "2m"
spec:
  provider: azure
  secretObjects:
    - secretName: {{ .Values.backend.aks.secretName }}
      type: Opaque
      data:
        - objectName: MONGO-URI
          key: MONGO_URI
        - objectName: SECRET-KEY
          key: SECRET_KEY
        - objectName: ENCRYPTION-KEY
          key: ENCRYPTION_KEY
        - objectName: AZURE-STORAGE-KEY
          key: AZURE_STORAGE_KEY
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.backend.azure.clientId }}"
    tenantId: "{{ .Values.backend.azure.tenantId }}"
    resourceGroup: "{{ .Values.backend.azure.resourceGroup }}"
    keyvaultName: "{{ .Values.backend.azure.keyVaultName }}"
    objects: |
      array:
        - |
          objectName: MONGO-URI
          objectType: secret
        - |
          objectName: SECRET-KEY
          objectType: secret
        - |
          objectName: ENCRYPTION-KEY
          objectType: secret
        - |
          objectName: AZURE-STORAGE-KEY
          objectType: secret
    syncSecret.enabled: "true"