apiVersion: v1
kind: Service
metadata:
  name: {{ include "traxxia.fullname" . }}-backend-service
  namespace: {{ .Values.traxxiabackend.aksconfig.namespace }}
spec:
  type: {{ .Values.traxxiabackend.service.type }}
  # loadBalancerIP: {{ .Values.traxxiabackend.service.ip }}
  selector:
    app: {{ include "traxxia.name" . }}-backend-app
  ports:
    - protocol: TCP
      port: {{ .Values.traxxiabackend.service.port }}
      targetPort: {{ .Values.traxxiabackend.app.port }}
