apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
  namespace: {{ .Values.backend.deployment.namespace }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: {{ include "traxxia.name" . }}-backend-app
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.application.containerPort }}
