apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "traxxia.fullname" . }}-backend-deployment
  namespace: {{ .Values.backend.deployment.namespace }}
spec:
  replicas: {{ .Values.backend.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ include "traxxia.name" . }}-backend-app
  template:
    metadata:
      labels:
        app: {{ include "traxxia.name" . }}-backend-app
    spec:
      serviceAccountName: {{ .Values.backend.aks.serviceAccount }}
      nodeSelector:
        agentpool: {{ .Values.backend.deployment.nodeSelectorLabel }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: "{{ .Values.backend.image.pullPolicy }}"
          ports:
            - containerPort: {{ .Values.backend.application.containerPort }}
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          env:
            {{- range .Values.backend.keyVault.secrets }}
            - name: {{ .alias }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.backend.aks.secretName }}
                  key: {{ .alias }}
            {{- end }}

      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "traxxia.fullname" . }}-backend-spc
