apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "traxxia.fullname" . }}-backend-deployment
  namespace: {{ .Values.traxxiabackend.aksconfig.namespace }}
spec:
  replicas: {{ .Values.traxxiabackend.aksconfig.replicas }}
  selector:
    matchLabels:
      app: {{ include "traxxia.name" . }}-backend-app
  template:
    metadata:
      labels:
        app: {{ include "traxxia.name" . }}-backend-app
    spec:
      # serviceAccountName: nuclios-backend-sa
      nodeSelector:
        agentpool: {{ .Values.traxxiabackend.aksconfig.nodePool.label }}
      containers:
        - name: backend
          image: "{{ .Values.traxxiabackend.image.repository }}:{{ .Values.traxxiabackend.image.tag }}"
          imagePullPolicy: "{{ .Values.traxxiabackend.image.pullPolicy }}"
          ports:
            - containerPort: {{ .Values.traxxiabackend.app.port }}