apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "traxxia.fullname" . }}-mastraai-spc
  namespace: {{ .Values.mastraai.deployment.namespace }}
  annotations:
    secrets-store.csi.k8s.io/rotation-poll-interval: "2m"
spec:
  provider: azure
  secretObjects:
    - secretName: {{ .Values.mastraai.aks.secretName }}
      type: Opaque
      data:
        - objectName: GROQ-API-KEY
          key: GROQ_API_KEY
        - objectName: MONGO-URI
          key: MONGO_URI
        - objectName: OPENAI-API-KEY
          key: OPENAI_API_KEY
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.mastraai.azure.clientId }}"
    tenantId: "{{ .Values.mastraai.azure.tenantId }}"
    resourceGroup: "{{ .Values.mastraai.azure.resourceGroup }}"
    keyvaultName: "{{ .Values.mastraai.azure.keyVaultName }}"
    objects: |
      array:
        - |
          objectName: GROQ-API-KEY
          objectType: secret
        - |
          objectName: MONGO-URI
          objectType: secret
        - |
          objectName: OPENAI-API-KEY
          objectType: secret
    syncSecret.enabled: "true"