apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mastraai.service.name }}
  namespace: {{ .Values.mastraai.deployment.namespace }}
spec:
  type: {{ .Values.mastraai.service.type }}
  selector:
    app: {{ include "traxxia.name" . }}-mastraai-app
  ports:
    - protocol: TCP
      port: {{ .Values.mastraai.service.port }}
      targetPort: {{ .Values.mastraai.application.containerPort }}
